dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: decide-alumno-1230
  strategy: git
  api_key:
    secure: TeXt7kCjag+pxWNNvXILlnCEt58WDV+ocak4En95oKOTatZ5hzG4FOUJStnY8xZe5UmjA1uazWEoFy9iq4fIetqr6t+GaartFgzwjeOtpsADAvcJwanBqme0cwuwmnnqoTt3ncnSfS8CZbe5zxbMr5Z3kPl23LUkz9fEL5FafuRt8q6GW9KDswwh5eDy7jQjgazgcnUQqdI7fdfTBdaFrCArtNDS6yV3IVz4zf21VANnOmr6DtXdktrjxTi0xef0hZwz0NyI6NxfhbMdpLS8TWhidbZnngbh6oKpFEzzWUfcPHvOmG+GD+WdvqJKuNOisAYKg1CMGvS3HYdWSVgja+kboS3WA54WKEodEtLlj2Qrpev3oGgoZd2Mt5/r66oISyOBEheBFZBqen1Q90CHQO4yerx/oySRgev6oAdwnVLJ2Z+ZoIJUGx529Kk4qHirohLYCVwku94WllpSb184/EHDAIKZAR7Q5P5BwuYPfItDBqUgNuRN0ZFqpeEc70G4+WbNd+ovEc0lvJDYxQlVDLLThYuviMM1ZYrgxaCGcysZvXm/KZGzjkTizIlOpluFCcLyu/OS5vAdf4alPOIF3Bg2t3RtVTCM51rSHXlqbx9X29ypXihyE6urHekQ9pxO9BEfdFxMk2OGAyTPGq1bA7mumR7hhWjlEHG0NPZcs7U=
